name: Deploy AWS Lambda Function

on:
    pull_request:
        branches:
            - main
            - develop
        types:
            - closed # PR이 닫혔을 때 (병합 포함)

    workflow_dispatch: # 수동 실행을 위한 트리거

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_LAMBDA_ENVIRONMENT_VARIABLES: ${{ secrets.AWS_LAMBDA_ENVIRONMENT_VARIABLES }}

        strategy:
            matrix:
                lambda:
                    - name: "knud-admin/cms-commit"
                      path: "cms-commit/src"
                      aws_function_name: "knud-admin-cms-commit"
                    - name: "knud-admin/cms-upload"
                      path: "cms-upload/src"
                      aws_function_name: "knud-admin-cms-upload"

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Build and Package Lambda Function - ${{ matrix.lambda.name }}
              run: |
                  cd ${{ github.workspace }}/${{ matrix.lambda.path }}
                  zip -r ../../${{ matrix.lambda.aws_function_name }}.zip .

            - name: Setup Environment Variables - ${{ matrix.lambda.name }}
              run: |
                  aws lambda update-function-configuration \
                    --function-name ${{ matrix.lambda.aws_function_name }} \
                    --environment '${{ env.AWS_LAMBDA_ENVIRONMENT_VARIABLES }}'

            - name: Deploy Lambda Function - ${{ matrix.lambda.name }}
              run: |
                  aws lambda update-function-code \
                    --function-name ${{ matrix.lambda.aws_function_name }} \
                    --zip-file fileb://${{ github.workspace }}/${{ matrix.lambda.aws_function_name }}.zip
